name: Snake Game

on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar Snake Game
        uses: Platane/snk/svg-only@v3  # Usa a versão corrigida sem 'set-output'
        with:
          github_user_name: DuhFr3itas
          outputs: dist/github-contribution-grid-snake.svg

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Criar branch output (se não existir)
        run: |
          git fetch origin output || git checkout -b output
          git pull origin output || echo "Branch output ainda não existe, criando agora."

      - name: Commit das mudanças
        run: |
          git add dist/
          git commit -m "Atualizando snake animation" || echo "Nenhuma mudança para commit"
          git push origin output  # Publica na branch output

      - name: Publicar no GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
